version: "3"
services:
  db:
    image: postgres:9.6-alpine
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgpass"
      POSTGRES_HOST_AUTH_METHOD: "trust"  
volumes:
  my_dbdata: